services:
  - name: musicgen-api
    type: web
    runtime: python
    buildCommand: ""
    startCommand: waitress-serve --host 0.0.0.0 --port 5000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
